const messages = [
	{
		id: 1,
		createDate: "2024-01-19 10:30:00",
		author_nick: "AIUser",
		author_full: "John Doe",
		initials: "JD",
		message_type: "question",
		content: "Czy możecie mi pomóc z zrozumieniem sieci neuronowych?",
	},
	{
		id: 2,
		createDate: "2024-01-18 15:45:00",
		author_nick: "TechGuru",
		author_full: "Alice Smith",
		initials: "AS",
		message_type: "response",
		content: "Oczywiście! Jak mogę ci pomóc?",
	},
	{
		id: 3,
		createDate: "2024-01-18 12:20:00",
		author_nick: "MLPro",
		author_full: "Bob Johnson",
		initials: "BJ",
		message_type: "question",
		content: "Dlaczego ważne jest unikanie overfittingu w modelach ML?",
	},
	{
		id: 4,
		createDate: "2024-01-17 18:10:00",
		author_nick: "AIEnthusiast",
		author_full: "Eva Brown",
		initials: "EB",
		message_type: "response",
		content:
			"Overfitting może prowadzić do złych generalizacji. Trzeba uważać na to!",
	},
	{
		id: 5,
		createDate: "2024-01-17 09:05:00",
		author_nick: "DeepLearner",
		author_full: "Chris Wilson",
		initials: "CW",
		message_type: "other",
		content: "Czy znacie dobre źródła do nauki reinforcement learning?",
	},
	{
		id: 6,
		createDate: "2024-01-16 14:55:00",
		author_nick: "CodeMaster",
		author_full: "Grace Lee",
		initials: "GL",
		message_type: "other",
		content:
			"Jaki język programowania preferujecie do projektów związanych z AI?",
	},
	{
		id: 7,
		createDate: "2024-01-16 08:40:00",
		author_nick: "AIGuru",
		author_full: "Michael Wang",
		initials: "MW",
		message_type: "response",
		content:
			"Myślę, że Python jest doskonały do projektów związanych z AI. Łatwy i potężny!",
	},
	{
		id: 8,
		createDate: "2024-01-15 17:30:00",
		author_nick: "NeuralNet",
		author_full: "Sophie Turner",
		initials: "ST",
		message_type: "question",
		content: "Czy ktoś ma doświadczenie z analizą dużych zbiorów danych?",
	},
	{
		id: 9,
		createDate: "2024-01-15 11:15:00",
		author_nick: "DataWizard",
		author_full: "David White",
		initials: "DW",
		message_type: "response",
		content: "Tak, pracuję z dużymi danymi. Jakie masz pytania?",
	},
	{
		id: 10,
		createDate: "2024-01-14 16:20:00",
		author_nick: "AIExplorer",
		author_full: "Emma Davis",
		initials: "ED",
		message_type: "question",
		content: "Jakie są najlepsze narzędzia do wizualizacji danych w AI?",
	},
	{
		id: 11,
		createDate: "2024-01-14 09:50:00",
		author_nick: "CodeNinja",
		author_full: "Ryan Chang",
		initials: "RC",
		message_type: "response",
		content:
			"Matplotlib i Seaborn są popularne w środowisku Pythona. Czy próbowałeś je już?",
	},
	{
		id: 12,
		createDate: "2024-01-13 14:35:00",
		author_nick: "AIFan",
		author_full: "Olivia Miller",
		initials: "OM",
		message_type: "question",
		content:
			"Czy ktoś zna ciekawe projekty z użyciem generatywnych modeli adversarialnych?",
	},
	{
		id: 13,
		createDate: "2024-01-13 08:25:00",
		author_nick: "MLMaster",
		author_full: "Daniel Chen",
		initials: "DC",
		message_type: "response",
		content:
			"Mogę polecić projekt DeepArt. Bardzo fascynujące zastosowanie GAN.",
	},
	{
		id: 14,
		createDate: "2024-01-12 16:15:00",
		author_nick: "AIStudent",
		author_full: "Sophia Kim",
		initials: "SK",
		message_type: "question",
		content:
			"Potrzebuję pomocy z implementacją algorytmu genetycznego. Ktoś może podać wskazówki?",
	},
	{
		id: 15,
		createDate: "2024-01-12 10:40:00",
		author_nick: "TechGeek",
		author_full: "Nathan Martin",
		initials: "NM",
		message_type: "response",
		content:
			"Oczywiście! W czym konkretnie masz problem z algorytmem genetycznym?",
	},
	{
		id: 16,
		createDate: "2024-01-11 15:20:00",
		author_nick: "AICoder",
		author_full: "Lily Johnson",
		initials: "LJ",
		message_type: "question",
		content: "Co sądzicie o etycznym użyciu sztucznej inteligencji?",
	},
	{
		id: 17,
		createDate: "2024-01-11 09:10:00",
		author_nick: "DataWhiz",
		author_full: "Jake Williams",
		initials: "JW",
		message_type: "response",
		content:
			"Etyka jest kluczowa. Powinniśmy dbać o odpowiedzialne stosowanie AI.",
	},
	{
		id: 18,
		createDate: "2024-01-10 14:55:00",
		author_nick: "MLNewbie",
		author_full: "Mia Taylor",
		initials: "MT",
		message_type: "other",
		content: "Czy ktoś poleca jakieś dobre kursy online z machine learning?",
	},
	{
		id: 19,
		createDate: "2024-01-10 08:45:00",
		author_nick: "AIResearcher",
		author_full: "Aaron Davis",
		initials: "AD",
		message_type: "response",
		content: "Coursera i edX mają wiele świetnych kursów ML. Sprawdź je!",
	},
	{
		id: 20,
		createDate: "2024-01-09 17:30:00",
		author_nick: "CodeEnthusiast",
		author_full: "Hannah Wilson",
		initials: "HW",
		message_type: "question",
		content:
			"Ktoś próbował implementować algorytmy uczenia maszynowego na urządzeniach IoT?",
	},
	{
		id: 21,
		createDate: "2024-01-09 17:25:00",
		author_nick: "CodeEnthusiast",
		author_full: "Hannah Wilson",
		initials: "HW",
		message_type: "other",
		content: "Świetnie jest porozmawiać o AI!",
	},
	{
		id: 22,
		createDate: "2024-01-09 09:10:00",
		author_nick: "DataWhiz",
		author_full: "Jake Williams",
		initials: "JW",
		message_type: "other",
		content: "Rozpoczynam dyskusję o AI!",
	},
];